#!/usr/bin/env node
/**
 *
 * 本地启动
 * 例如：
 *   - ./scripts/dev
 */

import {commandStandardExecutor} from '@142vip/utils'

(async () => await commandStandardExecutor([
  'pnpm build:mark-map',
  'pnpm dev'
]))()
