#!/bin/bash

##
## 自动格式化
##  - 代码
##  - markdown文档
## 使用:
  #    - ./scripts/lint
## 参考链接：
##   - https://eslint.org/docs/latest/use/getting-started
##   - https://github.com/igorshubovych/markdownlint-cli
##

# 设置 PATH 环境变量，避免command not found问题
export PATH="$(pnpm bin):$PATH"

# ESLint格式化代码
eslint --fix --ext .js,.ts,.vue --ignore-path .gitignore .

# markdown-cli格式化markdown 文档
markdownlint '**/*.md'  -c .markdownlint.js -p .markdownlintignore --fix

