#!/usr/bin/env node
/**
 * 版本发布脚本
 * 链接：https://jstools.dev/version-bump-prompt/
 * 使用: ./scripts/release
 */

const {execShell} = require("./.exec");


// 利用commit-and-tag-version生成changelog文档，并跳过commit、tag操作
const generateChangeLog='pnpm commit-and-tag-version && git add CHANGELOG.md'
// git提交信息
const commitInfo='chore(release): publish v%s'

const releaseCommands=
    "bumpp " +
    "--preid alpha "+
    `--execute= "${generateChangeLog}" `+
    `--commit "${commitInfo}" `+
    "--all "+
    "--tag "+
    "--push "

;(async ()=>{
    await execShell(releaseCommands)
})()