## 参考资料：https://v2.vuepress.vuejs.org/zh/guide/deployment.html#github-pages
name: gh-deploy
on:
  push:
    branches:
      - master
      - next
  workflow_dispatch:

jobs:
  deploy-github:
    name: "部署到Github"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 14.20.1
          # 缓存 pnpm 依赖
          cache: pnpm

      # 运行构建脚本
      - name: Build VuePress Site
        run:
          PROXY_DOMAIN=true pnpm build

      - name: Deploy to GitHub Page
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: pages/github
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
