name: Github-Version-Release

on:
  ## 当以 'v' 开头的标签推送到master时触发工作流程
  push:
    branches:
      - master
      - feat/test-release
#    tags:
#      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.2

      - name: PNPM Install
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      ### 打成压缩包
      - name: Create Zip Archive
        run: |
          zip -r 408CSFamily.zip . \
          -x "node_modules/*"

      # 提取版本号
      - name: Extract Version
        id: extract_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"


      # 创建发布版本
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          release_name: v${{ steps.extract_version.outputs.version }}
          body: |
            本次发布包含了一些新功能、Bug 修复和改进。
            ### Features
            
            ### Bug Fixes

      ## 更新资源
      - name: Upload Assets
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./408CSFamily.zip
          asset_name: 408CSFamily.zip
          asset_content_type: application/zip