name: Github-Version-Release

on:
  ## 当以 'v' 开头的标签推送到master时触发工作流程
  push:
    branches:
      - master
      - feat/test-release
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.2

      - name: PNPM Install
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      ### 打成压缩包
      - name: Create Zip Archive
        run: |
          zip -r 408CSFamily.zip . \
          -x "node_modules/*"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Release ${{ github.sha }}
            Version: ${{ steps.extract_package_info.outputs.version }}
            **概述**
            本次发布包含了一些新功能、bug 修复和改进。
            **新功能**
            ${{ steps.generate_changelog.outputs.new_features }}
            **Bug 修复**
            ${{ steps.generate_changelog.outputs.bug_fixes }}
            **改进和优化**
            ${{ steps.generate_changelog.outputs.improvements }}
            **重要提示**
            - 注意：XXX 配置发生了变化，请更新您的配置文件。
            - 请务必查看更新的操作指南，以获取有关如何使用新功能的详细信息。
            **链接和资源**
            - 项目文档：[链接](https://example.com/docs)
            - 示例代码：[链接](https://github.com/example/repo/tree/${{ github.sha }}/examples)
            **鸣谢**
            感谢以下贡献者对本次发布的帮助和贡献：
            ${{ steps.generate_contributors.outputs.contributors }}
#          body_path: CHANGELOG.md
          ## 是否为草稿、是否为预发布
          draft: false
          prerelease: false

      - name: Upload Assets
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./408CSFamily.zip
          asset_name: 408CSFamily.zip
          asset_content_type: application/zip