# 自动部署到vercel上
name: Vercel Deploy
on:
  push:
    branches:
      - master
      - next
      - feat/fix-ci
#  pull_request:
#    branches:
#      - master
#      - next
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

#      - name: sync to vercel
#        uses: amondnet/vercel-action@v20
#        with:
#          vercel-token: ${{ secrets.VERCEL_TOKEN }}
#          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
#          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
#

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.2

      - name: PNPM Install
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Login to Vercel
        uses: vercel/login@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel --prod
